In [2]:
import pickle
def save_file(file_name,data):
    open_file = open(file_name, "wb")
    pickle.dump(data, open_file)
    open_file.close()

def open_file(file_name):
    open_file = open(file_name, "rb")
    Dataset = pickle.load(open_file)
    open_file.close()
    return Dataset

In [3]:
file_name="../data/fedavg Mnist flip shuffle noisy.pkl"
fedavg=open_file(file_name)

In [4]:
a=fedavg[-4]

In [5]:
import tensorflow as tf
from tensorflow.keras.losses import CosineSimilarity
from tensorflow.keras import backend as K

def cosine_similarity(tensor1, tensor2):
    # Normalize the tensors
    tensor1_normalized = tf.nn.l2_normalize(tensor1, axis=-1)
    tensor2_normalized = tf.nn.l2_normalize(tensor2, axis=-1)

    # Calculate the cosine similarity
    cos_similarity = K.mean(CosineSimilarity(axis=-1)(tensor1_normalized, tensor2_normalized))

    return cos_similarity


similarity_score = cosine_similarity(a[0][0], a[0][0])
print("Cosine Similarity:", similarity_score.numpy())


Cosine Similarity: -1.0


In [6]:
def model_cosine_similarity(weight1, weight2):
    bla=[]
    for i in range(len(weight1)):
        bla.append(cosine_similarity(weight1[i], weight2[i]))
    return sum(bla) / len(bla)

In [7]:
def krum(weight_list):
    
    bla=[]
    
    for i in range(len(weight_list)):
        sla=[]
        for j in range(len(weight_list)):
            sla.append(model_cosine_similarity(weight_list[i],weight_list[j]))
        bla.append(sum(sla) / len(sla))
    print (min(bla))
    return weight_list[bla.index(min(bla))]

In [8]:
krum(a)

tf.Tensor(-0.96670234, shape=(), dtype=float32)


[<tf.Tensor: shape=(784, 200), dtype=float32, numpy=
 array([[-0.06600284, -0.03788288, -0.03212716, ..., -0.04340594,
         -0.03162709,  0.0303961 ],
        [ 0.04390918, -0.02384582,  0.00554874, ...,  0.05144076,
         -0.02991999,  0.05105833],
        [ 0.05826649,  0.04549345, -0.03060922, ...,  0.03978813,
          0.0089675 ,  0.04471927],
        ...,
        [ 0.04593035,  0.03963523, -0.07227715, ...,  0.00476207,
          0.01929413, -0.01753505],
        [-0.00731316,  0.02193984, -0.05303136, ...,  0.04359926,
          0.02629308,  0.04763789],
        [-0.06795572,  0.07734074,  0.00270741, ...,  0.03820878,
          0.06287692,  0.04931433]], dtype=float32)>,
 <tf.Tensor: shape=(200,), dtype=float32, numpy=
 array([ 0.03750113,  0.04018898, -0.00081508,  0.00874702,  0.04688033,
         0.00726428,  0.01254437,  0.04891712,  0.02604533, -0.00684474,
         0.04043762, -0.01635501, -0.00853395,  0.03155166,  0.04933766,
        -0.00120393,  0.03541163,  0

In [38]:
median_tensor

<tf.Tensor: shape=(784, 200), dtype=float32, numpy=
array([[-0.07223156, -0.04370273, -0.03304498, ..., -0.03026067,
        -0.02815351,  0.02535768],
       [ 0.04376364, -0.02891858,  0.00701842, ...,  0.06105437,
        -0.0251136 ,  0.04912676],
       [ 0.053332  ,  0.03867402, -0.03101271, ...,  0.0515895 ,
         0.0097781 ,  0.03956761],
       ...,
       [ 0.04283068,  0.03374952, -0.06923658, ...,  0.01567153,
         0.02268914, -0.02005144],
       [-0.01278684,  0.01507946, -0.05251002, ...,  0.05468993,
         0.02928582,  0.04106782],
       [-0.07234818,  0.07204089,  0.00395129, ...,  0.04921023,
         0.06606101,  0.04392981]], dtype=float32)>

In [37]:
import tensorflow as tf
import tensorflow_probability as tfp

# Assuming your list of tensors is called 'tensor_list'
tensor_list = [a[0][0],a[1][0],a[2][0],a[3][0]]  # Replace this with your list of tensors

# Convert the list of tensors to a TensorFlow tensor
stacked_tensors = tf.stack(tensor_list)

# Calculate the element-wise median using the percentile function from TensorFlow Probability
median_tensor = tfp.stats.percentile(stacked_tensors, q=50.0, axis=0)

# Now 'median_tensor' contains the element-wise median values of the tensors in 'tensor_list'


In [25]:
import tensorflow as tf
import tensorflow_probability as tfp

trim_percentage = 10  # Trim 10% from both ends

# Convert the list of tensors to a TensorFlow tensor
stacked_tensors = tf.stack(tensor_list)

# Sort the elements along the specified axis
sorted_tensors = tf.sort(stacked_tensors, axis=0)

# Calculate the number of elements to trim from both ends
num_trim = int(sorted_tensors.shape[0] * trim_percentage / 100)

# Remove elements from both ends
trimmed_values = sorted_tensors[num_trim:-num_trim, :]

# Calculate the mean of the trimmed values
trimmed_mean_tensor = tf.reduce_mean(trimmed_values, axis=0)

# Now 'trimmed_mean_tensor' contains the trimmed mean values of the tensors in 'tensor_list'


In [26]:
trimmed_values


<tf.Tensor: shape=(0, 784, 200), dtype=float32, numpy=array([], shape=(0, 784, 200), dtype=float32)>

In [35]:
num_trim = 1

# Remove elements from both ends
trimmed_values = sorted_tensors[num_trim:-num_trim, :]

# Calculate the mean of the trimmed values
trimmed_mean_tensor = tf.reduce_mean(trimmed_values, axis=0)

# Now 'trimmed_mean_tensor' contains the trimmed mean values of the tensors in 'tensor_list'


In [36]:
trimmed_mean_tensor

<tf.Tensor: shape=(784, 200), dtype=float32, numpy=
array([[-0.07269196, -0.04395746, -0.03318259, ..., -0.03111107,
        -0.02842806,  0.02477499],
       [ 0.04361841, -0.02911125,  0.00689292, ...,  0.06053296,
        -0.0254186 ,  0.04875575],
       [ 0.05288666,  0.03845204, -0.03118146, ...,  0.05092775,
         0.00965181,  0.03911385],
       ...,
       [ 0.04246023,  0.03343218, -0.06926637, ...,  0.01501078,
         0.02244058, -0.02054426],
       [-0.01331427,  0.01483625, -0.05266879, ...,  0.05402736,
         0.02909078,  0.04051841],
       [-0.07270855,  0.07178603,  0.00391753, ...,  0.04872624,
         0.06584881,  0.04331933]], dtype=float32)>

In [41]:
import math

In [44]:
def trimmed_mean(weight, trim_percent):
    num_trim = math.ceil(len(weight)*trim_percent)
    final_weight=[]
    for i in range(len(weight[0])):
        tensor_list=[]
        for j in range(len(weight)):
            tensor_list.append(weight[j][i])
        # Convert the list of tensors to a TensorFlow tensor
        stacked_tensors = tf.stack(tensor_list)

        # Sort the elements along the specified axis
        sorted_tensors = tf.sort(stacked_tensors, axis=0)
        
        # Remove elements from both ends
        trimmed_values = sorted_tensors[num_trim:-num_trim, :]

        # Calculate the mean of the trimmed values
        trimmed_mean_tensor = tf.reduce_mean(trimmed_values, axis=0)
        
        final_weight.append(trimmed_mean_tensor)
    
    return final_weight


            
    

In [47]:
bla=trimmed_mean(a, trim_percent=.3)

In [49]:
def median(weight):
    final_weight=[]
    for i in range(len(weight[0])):
        tensor_list=[]
        for j in range(len(weight)):
            tensor_list.append(weight[j][i])
        # Convert the list of tensors to a TensorFlow tensor
        stacked_tensors = tf.stack(tensor_list)

        median_tensor=tfp.stats.percentile(stacked_tensors, q=50.0, axis=0)
        
        final_weight.append(median_tensor)
    
    return final_weight


In [50]:
sla= median(a)

In [51]:
sla

[<tf.Tensor: shape=(784, 200), dtype=float32, numpy=
 array([[-0.06509966, -0.03792556, -0.03255203, ..., -0.045099  ,
         -0.03254909,  0.03080695],
        [ 0.0434106 , -0.0238793 ,  0.00534978, ...,  0.04980946,
         -0.03043442,  0.05062573],
        [ 0.05880396,  0.04579739, -0.03081616, ...,  0.03864603,
          0.00911622,  0.0453837 ],
        ...,
        [ 0.04618701,  0.0390556 , -0.07290006, ...,  0.00292398,
          0.01968495, -0.01807931],
        [-0.00687747,  0.02228056, -0.05333045, ...,  0.04162642,
          0.02647278,  0.04847243],
        [-0.06726092,  0.07674095,  0.00250006, ...,  0.03668167,
          0.06319889,  0.05006681]], dtype=float32)>,
 <tf.Tensor: shape=(200,), dtype=float32, numpy=
 array([ 3.79120260e-02,  4.01889756e-02,  9.60021207e-05,  1.00896005e-02,
         4.99129109e-02,  6.20998489e-03,  1.11565832e-02,  5.02553508e-02,
         2.79941261e-02, -9.11430456e-03,  4.18499522e-02, -1.86711159e-02,
        -9.07317828e-03,  3

In [52]:
bla

[<tf.Tensor: shape=(784, 200), dtype=float32, numpy=
 array([[-0.06504185, -0.03812577, -0.03254911, ..., -0.0448406 ,
         -0.03206709,  0.03058983],
        [ 0.04330434, -0.02403585,  0.00536694, ...,  0.0499351 ,
         -0.03018596,  0.05059014],
        [ 0.05891858,  0.04572579, -0.03084137, ...,  0.03861116,
          0.00927416,  0.04509591],
        ...,
        [ 0.04628487,  0.0390165 , -0.07315312, ...,  0.00301756,
          0.01971761, -0.01805881],
        [-0.00682062,  0.02223551, -0.05352591, ...,  0.04189399,
          0.02653086,  0.04808839],
        [-0.06711307,  0.07671525,  0.00237579, ...,  0.03675976,
          0.0632763 ,  0.04973306]], dtype=float32)>,
 <tf.Tensor: shape=(200,), dtype=float32, numpy=
 array([ 3.74901444e-02,  4.00465168e-02, -8.28877091e-06,  1.00145126e-02,
         4.93033044e-02,  5.89552056e-03,  1.09907305e-02,  4.99121286e-02,
         2.79406738e-02, -8.74045305e-03,  4.16316986e-02, -1.83786377e-02,
        -9.16766003e-03,  3